import type {
  User,
  AffiliateStats,
  AffiliateLink,
  MarketingMaterial,
  Payment,
  Product,
  Customer,
  Order,
  ResellerStats,
} from "./types";

export const currentAffiliateUser: User = {
  id: "aff-001",
  name: "Ana Paula Silva",
  email: "ana.silva@email.com",
  role: "afiliado",
  avatarInitials: "AS",
  joinedAt: "2024-03-15",
  status: "ativo",
};

export const currentResellerUser: User = {
  id: "rev-001",
  name: "Beatriz Santos",
  email: "beatriz@loja.com",
  role: "revendedor",
  avatarInitials: "BS",
  joinedAt: "2024-01-10",
  status: "ativo",
};

export const affiliateStats: AffiliateStats = {
  totalClicks: 4382,
  conversions: 312,
  conversionRate: 7.12,
  pendingCommission: 847.5,
  totalEarned: 6240.0,
  thisMonthEarned: 1120.0,
};

export const affiliateLinks: AffiliateLink[] = [
  {
    id: "lnk-001",
    name: "Página Principal",
    url: "https://lilisampedro.com.br",
    shortUrl: "https://lili.br/aff/ana001",
    clicks: 1842,
    conversions: 134,
    commission: 2680.0,
    createdAt: "2024-03-15",
    status: "ativo",
  },
  {
    id: "lnk-002",
    name: "Curso de Maquiagem",
    url: "https://lilisampedro.com.br/cursos/maquiagem",
    shortUrl: "https://lili.br/aff/ana002",
    clicks: 1240,
    conversions: 98,
    commission: 1960.0,
    createdAt: "2024-04-02",
    status: "ativo",
  },
  {
    id: "lnk-003",
    name: "Kit Beleza Premium",
    url: "https://lilisampedro.com.br/produtos/kit-premium",
    shortUrl: "https://lili.br/aff/ana003",
    clicks: 890,
    conversions: 67,
    commission: 1340.0,
    createdAt: "2024-04-20",
    status: "ativo",
  },
  {
    id: "lnk-004",
    name: "Black Friday 2024",
    url: "https://lilisampedro.com.br/blackfriday",
    shortUrl: "https://lili.br/aff/ana004",
    clicks: 410,
    conversions: 13,
    commission: 260.0,
    createdAt: "2024-11-20",
    status: "inativo",
  },
];

export const marketingMaterials: MarketingMaterial[] = [
  {
    id: "mat-001",
    title: "Banner Principal 728x90",
    type: "banner",
    description: "Banner horizontal para uso em blogs e sites parceiros.",
    format: "JPG/PNG",
    dimensions: "728x90px",
    downloadUrl: "#",
    previewColor: "from-rose-400 to-pink-600",
  },
  {
    id: "mat-002",
    title: "Banner Quadrado 500x500",
    type: "banner",
    description: "Ideal para redes sociais como Instagram e Facebook.",
    format: "JPG/PNG",
    dimensions: "500x500px",
    downloadUrl: "#",
    previewColor: "from-purple-400 to-violet-600",
  },
  {
    id: "mat-003",
    title: "Banner Vertical 300x600",
    type: "banner",
    description: "Half page para anúncios em portais e revistas digitais.",
    format: "JPG/PNG",
    dimensions: "300x600px",
    downloadUrl: "#",
    previewColor: "from-pink-400 to-rose-600",
  },
  {
    id: "mat-004",
    title: "Texto Pronto - Instagram",
    type: "texto",
    description: "Legenda otimizada para posts no Instagram com hashtags.",
    content:
      "✨ Já conhece os produtos da @lilisampedro? Cosméticos de alta qualidade para realçar sua beleza natural! Acesse pelo link na bio e aproveite as ofertas exclusivas. #beleza #maquiagem #lilisampedro #cosmeticos",
    previewColor: "from-amber-400 to-orange-500",
  },
  {
    id: "mat-005",
    title: "Texto Pronto - WhatsApp",
    type: "texto",
    description: "Mensagem formatada para envio no WhatsApp e grupos.",
    content:
      "🌸 *Olá! Conhece a Lili Sampedro?* 🌸\n\nEla tem os melhores produtos de beleza com qualidade incomparável!\n\n✅ Entrega para todo o Brasil\n✅ Pagamento facilitado\n✅ Produtos testados e aprovados\n\nAcesse agora: [SEU_LINK]",
    previewColor: "from-green-400 to-emerald-600",
  },
  {
    id: "mat-006",
    title: "Template E-mail Marketing",
    type: "email",
    description: "Template HTML responsivo para campanhas de e-mail.",
    downloadUrl: "#",
    previewColor: "from-blue-400 to-indigo-600",
  },
  {
    id: "mat-007",
    title: "Vídeo Apresentação 60s",
    type: "video",
    description: "Vídeo curto para stories e reels com os principais produtos.",
    downloadUrl: "#",
    previewColor: "from-red-400 to-pink-600",
  },
];

export const payments: Payment[] = [
  {
    id: "pag-001",
    type: "saque",
    amount: 500.0,
    status: "pago",
    date: "2025-04-30",
    description: "Saque referente a abril/2025",
    method: "PIX",
    transactionId: "TXN20250430001",
  },
  {
    id: "pag-002",
    type: "comissao",
    amount: 420.0,
    status: "pago",
    date: "2025-04-15",
    description: "Comissão - vendas período 01/04 a 15/04",
    transactionId: "TXN20250415001",
  },
  {
    id: "pag-003",
    type: "comissao",
    amount: 700.0,
    status: "pendente",
    date: "2025-05-01",
    description: "Comissão - vendas período 16/04 a 30/04",
  },
  {
    id: "pag-004",
    type: "saque",
    amount: 350.0,
    status: "processando",
    date: "2025-05-05",
    description: "Saque solicitado em 05/05/2025",
    method: "PIX",
  },
  {
    id: "pag-005",
    type: "comissao",
    amount: 147.5,
    status: "pendente",
    date: "2025-05-07",
    description: "Comissão - vendas período 01/05 a 07/05",
  },
  {
    id: "pag-006",
    type: "saque",
    amount: 800.0,
    status: "pago",
    date: "2025-03-31",
    description: "Saque referente a março/2025",
    method: "PIX",
    transactionId: "TXN20250331001",
  },
];

export const products: Product[] = [
  {
    id: "prod-001",
    name: "Base Líquida Matte Perfeita",
    category: "Maquiagem",
    costPrice: 45.0,
    suggestedPrice: 129.9,
    resellerPrice: 65.0,
    stock: 84,
    sku: "LS-BASE-001",
    imageColor: "from-rose-200 to-pink-300",
    description: "Base de alta cobertura com acabamento matte duradouro, FPS 30.",
  },
  {
    id: "prod-002",
    name: "Batom Cremoso Luxo 12h",
    category: "Maquiagem",
    costPrice: 18.0,
    suggestedPrice: 59.9,
    resellerPrice: 28.0,
    stock: 156,
    sku: "LS-BAT-001",
    imageColor: "from-red-300 to-rose-500",
    description: "Batom de longa duração com 15 opções de cor, hidratante.",
  },
  {
    id: "prod-003",
    name: "Paleta de Sombras Rose Gold",
    category: "Maquiagem",
    costPrice: 62.0,
    suggestedPrice: 189.9,
    resellerPrice: 95.0,
    stock: 43,
    sku: "LS-SOB-001",
    imageColor: "from-amber-200 to-yellow-400",
    description: "18 cores entre matte, acetinado e glitter. Pigmentação profissional.",
  },
  {
    id: "prod-004",
    name: "Sérum Vitamina C Iluminador",
    category: "Skincare",
    costPrice: 55.0,
    suggestedPrice: 159.9,
    resellerPrice: 82.0,
    stock: 67,
    sku: "LS-SER-001",
    imageColor: "from-orange-200 to-amber-400",
    description: "Sérum com 20% de Vitamina C pura para pele radiante e uniforme.",
  },
  {
    id: "prod-005",
    name: "Kit Skincare Completo",
    category: "Skincare",
    costPrice: 120.0,
    suggestedPrice: 349.9,
    resellerPrice: 185.0,
    stock: 28,
    sku: "LS-KIT-001",
    imageColor: "from-teal-200 to-cyan-400",
    description: "Kit com limpador, tônico, sérum, hidratante e protetor solar.",
  },
  {
    id: "prod-006",
    name: "Perfume Floral Intense 50ml",
    category: "Fragrâncias",
    costPrice: 85.0,
    suggestedPrice: 249.9,
    resellerPrice: 130.0,
    stock: 52,
    sku: "LS-PERF-001",
    imageColor: "from-purple-200 to-violet-400",
    description: "Fragrância floral oriental com notas de rosa, jasmim e baunilha.",
  },
  {
    id: "prod-007",
    name: "Máscara Capilar Reconstrução",
    category: "Cabelos",
    costPrice: 35.0,
    suggestedPrice: 99.9,
    resellerPrice: 52.0,
    stock: 91,
    sku: "LS-CAP-001",
    imageColor: "from-emerald-200 to-green-400",
    description: "Máscara intensiva com queratina e argan para cabelos danificados.",
  },
];

export const customers: Customer[] = [
  {
    id: "cli-001",
    name: "Maria Fernanda Costa",
    email: "mfernanda@gmail.com",
    phone: "(11) 99999-1234",
    city: "São Paulo",
    state: "SP",
    totalOrders: 8,
    totalSpent: 1240.5,
    lastOrder: "2025-04-28",
    status: "ativo",
  },
  {
    id: "cli-002",
    name: "Juliana Rodrigues",
    email: "juliana.r@outlook.com",
    phone: "(21) 98888-5678",
    city: "Rio de Janeiro",
    state: "RJ",
    totalOrders: 5,
    totalSpent: 890.0,
    lastOrder: "2025-05-01",
    status: "ativo",
  },
  {
    id: "cli-003",
    name: "Carla Mendes",
    email: "carla.mendes@yahoo.com",
    phone: "(31) 97777-9012",
    city: "Belo Horizonte",
    state: "MG",
    totalOrders: 12,
    totalSpent: 2380.0,
    lastOrder: "2025-04-20",
    status: "ativo",
  },
  {
    id: "cli-004",
    name: "Patrícia Alves",
    email: "patricia.a@email.com",
    phone: "(41) 96666-3456",
    city: "Curitiba",
    state: "PR",
    totalOrders: 3,
    totalSpent: 456.8,
    lastOrder: "2025-03-15",
    status: "ativo",
  },
  {
    id: "cli-005",
    name: "Renata Oliveira",
    email: "renata.o@gmail.com",
    phone: "(51) 95555-7890",
    city: "Porto Alegre",
    state: "RS",
    totalOrders: 1,
    totalSpent: 189.9,
    lastOrder: "2025-02-10",
    status: "inativo",
  },
  {
    id: "cli-006",
    name: "Amanda Pereira",
    email: "amanda.p@hotmail.com",
    phone: "(71) 94444-2345",
    city: "Salvador",
    state: "BA",
    totalOrders: 6,
    totalSpent: 1120.0,
    lastOrder: "2025-05-05",
    status: "ativo",
  },
];

export const orders: Order[] = [
  {
    id: "ped-001",
    customerId: "cli-003",
    customerName: "Carla Mendes",
    products: [
      { productId: "prod-001", productName: "Base Líquida Matte Perfeita", quantity: 2, unitPrice: 65.0, subtotal: 130.0 },
      { productId: "prod-003", productName: "Paleta de Sombras Rose Gold", quantity: 1, unitPrice: 95.0, subtotal: 95.0 },
    ],
    total: 225.0,
    profit: 103.0,
    status: "entregue",
    date: "2025-04-20",
    paymentMethod: "PIX",
  },
  {
    id: "ped-002",
    customerId: "cli-006",
    customerName: "Amanda Pereira",
    products: [
      { productId: "prod-004", productName: "Sérum Vitamina C Iluminador", quantity: 1, unitPrice: 82.0, subtotal: 82.0 },
      { productId: "prod-007", productName: "Máscara Capilar Reconstrução", quantity: 2, unitPrice: 52.0, subtotal: 104.0 },
    ],
    total: 186.0,
    profit: 96.0,
    status: "enviado",
    date: "2025-05-05",
    paymentMethod: "Cartão",
  },
  {
    id: "ped-003",
    customerId: "cli-001",
    customerName: "Maria Fernanda Costa",
    products: [
      { productId: "prod-005", productName: "Kit Skincare Completo", quantity: 1, unitPrice: 185.0, subtotal: 185.0 },
    ],
    total: 185.0,
    profit: 65.0,
    status: "confirmado",
    date: "2025-05-06",
    paymentMethod: "PIX",
  },
  {
    id: "ped-004",
    customerId: "cli-002",
    customerName: "Juliana Rodrigues",
    products: [
      { productId: "prod-006", productName: "Perfume Floral Intense 50ml", quantity: 1, unitPrice: 130.0, subtotal: 130.0 },
      { productId: "prod-002", productName: "Batom Cremoso Luxo 12h", quantity: 3, unitPrice: 28.0, subtotal: 84.0 },
    ],
    total: 214.0,
    profit: 129.0,
    status: "pendente",
    date: "2025-05-07",
    paymentMethod: "Boleto",
  },
  {
    id: "ped-005",
    customerId: "cli-004",
    customerName: "Patrícia Alves",
    products: [
      { productId: "prod-002", productName: "Batom Cremoso Luxo 12h", quantity: 5, unitPrice: 28.0, subtotal: 140.0 },
    ],
    total: 140.0,
    profit: 50.0,
    status: "cancelado",
    date: "2025-03-15",
    paymentMethod: "Cartão",
  },
];

export const resellerStats: ResellerStats = {
  totalRevenue: 18420.0,
  totalProfit: 7840.0,
  totalOrders: 94,
  totalCustomers: 6,
  thisMonthRevenue: 3200.0,
  thisMonthProfit: 1380.0,
  averageOrderValue: 195.96,
  topProduct: "Base Líquida Matte Perfeita",
};
